trigger:
- master
- dev

jobs:
- job: build_debug_windows_vs2022
  displayName: 'Build Debug - Windows (VS2022)'
  pool:
    vmImage: 'windows-2022'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
    displayName: 'Setting up Python 3.x'
  - script: |
      python -m pip install aqtinstall
    displayName: 'Installing aqtinstall'
  - bash: |
      mkdir qt
      cd qt
      python -m aqt install-qt windows desktop 6.3.0 win64_msvc2019_64 -m qtcharts qtdatavis3d qtpositioning
      echo "##vso[task.setvariable variable=QT_DIR]$(Build.SourcesDirectory)\qt\6.3.0\msvc2019_64"
    displayName: 'Installing Qt 6.3.0'
  - script: |
      cd utils
      premake5 vs2022
    displayName: 'Generating Visual Studio Project Files'
  - task: VSBuild@1
    inputs:
      solution: '.generated\project\windows\vs2022\Shibboleth.sln'
      platform: 'x64'
      configuration: 'Debug'
      clean: true
      vsVersion: 'latest'
      maximumCpuCount: true
    displayName: 'Building with VS2022'

- job: build_debug_linux_gcc
  displayName: 'Build Debug - Linux (GCC)'
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    CC: gcc-10
    CXX: g++-10
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
    displayName: 'Setting up Python 3.x'
  - script: |
      python -m pip install aqtinstall
    displayName: 'Installing aqtinstall'
  - script: |
      mkdir qt
      cd qt
      python -m aqt install-qt linux desktop 6.3.0 gcc_64 -m qtcharts qtdatavis3d qtpositioning
      echo "##vso[task.setvariable variable=QT_DIR]$(Build.SourcesDirectory)\qt\6.3.0\gcc_64"
    displayName: 'Installing Qt 6.3.0'
  - script: |
      sudo apt-get install libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglx-dev libxcursor-dev libxinerama-dev libgtk-3-dev
    displayName: 'Installing Dependency Packages'
  - script: |
      cd utils
      chmod +xr ./premake5
      ./premake5 gmake2 --qt-force-libexec
    displayName: 'Generating GMake Project Files'
  - script: |
      cd .generated/project/linux/gmake2
      make clean
      make config=debug_x64 Gaff Gleam Esprit EASTL CodeGenerator FastXml LowLevel LowLevelAABB LowLevelDynamics PhysX PhysXCharacterKinematic PhysXCommon PhysXCooking PhysXExtensions PhysXFoundation PhysXPvdSDK PhysXTask PhysXVehicle SceneQuery SimulationController assimp imgui libpng libtiff Lua mimalloc minizip-ng mpack sqlite zlib-ng capstone GLFW zstd TracyClient TracyProfiler Engine Memory Catch2 CivetWeb JSONToMessagePack ReflectionHashDump ECS Resource MainLoop AllocatorTest ReflectionTest ECSTest
    displayName: 'Building with GCC'

- job: build_debug_linux_clang
  displayName: 'Build Debug - Linux (Clang)'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
    displayName: 'Setting up Python 3.x'
  - script: |
      python -m pip install aqtinstall
    displayName: 'Installing aqtinstall'
  - script: |
      mkdir qt
      cd qt
      python -m aqt install-qt linux desktop 6.3.0 gcc_64 -m qtcharts qtdatavis3d qtpositioning
      echo "##vso[task.setvariable variable=QT_DIR]$(Build.SourcesDirectory)/qt/6.3.0/gcc_64"
    displayName: 'Installing Qt 6.3.0'
  - script: |
      sudo apt-get install libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglx-dev libxcursor-dev libxinerama-dev libgtk-3-dev
    displayName: 'Installing Dependency Packages'
  - script: |
      cd utils
      chmod +xr ./premake5
      ./premake5 gmake2 --cc=clang --qt-force-libexec
    displayName: 'Generating GMake Project Files'
  - script: |
      cd .generated/project/linux/gmake2
      make clean
      make config=debug_x64 Gaff Gleam Esprit EASTL CodeGenerator FastXml LowLevel LowLevelAABB LowLevelDynamics PhysX PhysXCharacterKinematic PhysXCommon PhysXCooking PhysXExtensions PhysXFoundation PhysXPvdSDK PhysXTask PhysXVehicle SceneQuery SimulationController assimp imgui libpng libtiff Lua mimalloc minizip-ng mpack sqlite zlib-ng capstone GLFW zstd TracyClient TracyProfiler Engine Memory Catch2 CivetWeb JSONToMessagePack ReflectionHashDump ECS Resource MainLoop AllocatorTest ReflectionTest ECSTest
    displayName: 'Building with Clang'
