trigger:
- master
- dev

jobs:
- job: build_debug_windows_vs2022
  displayName: 'Build Debug - VS2022'
  pool:
    vmImage: 'windows-2022'
  steps:
  - script: |
      vcpkg install qtbase
      cd utils
      premake5 vs2022
  - task: VSBuild@1
    inputs:
      solution: '.generated\project\windows\vs2022\Shibboleth.sln'
      platform: 'x64'
      configuration: 'Debug'
      clean: true
      vsVersion: 'latest'
- job: build_debug_linux
  displayName: 'Build Debug - Linux'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      cd utils
      ./premake5 gmake2
      cd ../.generated/project/gmake2
      gmake clean
      gmake config=debug_x64 Gaff Gleam Esprit Engine FastXml LowLevel LowLevelAABB LowLevelDynamics PhysX PhysXCharacterKinematic PhysXCommon PhysXCooking PhysXExtensions PhysXFoundation PhysXPvdSDK PhysXTask PhysXVehicle SceneQuery SimulationController assimp Catch2 CivetWeb EASTL imgui libpng libtiff Lua mimalloc minizip mpack optick sqlite zlib-ng

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
