# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- dev

pool:
  vmImage: 'windows-latest'

jobs:
- job: Build Debug
  displayName: 'Build Debug'
  steps:
  - script: utils/premake5 vs2019
  - task: VSBuild@1
    inputs:
      solution: '.generated\project\windows\vs2019\Shibboleth.sln'
      platform: 'x64'
      configuration: 'Debug'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
