# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

# Configurations
# #############################################

INCLUDES += -I../../../../../src/Modules/EditorBasic/include -I../../../../../src/Dependencies/EASTL/include -I../../../../../src/Dependencies/rapidjson -I../../../../../src/Frameworks/Gaff/include -I../../../../../src/Frameworks/Gleam/include -I../../../../../src/Engine/Editor/include -I../../../../../src/Engine/Engine/include -I../../../../../src/Engine/Memory/include -I../../../../../src/Modules/ECS/include -I../../../../../src/Dependencies/wxWidgets/include -I../../../../../src/Dependencies/wxWidgets/include/msvc
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
	@echo Generating Gen_ReflectionInit.h for module EditorBasic!
	cd ../../../../../utils
	premake5 gen_module_header --module=EditorBasic
endef
define PRELINKCMDS
endef

ifeq ($(config),debug_x64)
RESCOMP = windres
TARGETDIR = ../../../../build/windows/gmake2/output/x64/Debug
TARGET = $(TARGETDIR)/EditorBasicModule64d.dll
OBJDIR = ../../../../build/windows/gmake2/intermediate/x64/Debug/EditorBasicModule
DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -D_DEBUG -DDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DwxUSE_ZLIB_H_IN_PATH -DWXUSINGDLL -D__WXMSW__
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Werror -ffast-math -Og -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Werror -ffast-math -Og -g -Wall -Wextra -std=c++1z -fno-rtti
LIBS += ../../../../build/windows/gmake2/output/x64/Debug/EditorBasic.lib ../../../../build/windows/gmake2/output/x64/Debug/Editor.lib ../../../../build/windows/gmake2/output/x64/Debug/Engine.lib ../../../../build/windows/gmake2/output/x64/Debug/Memory64d.lib ../../../../build/windows/gmake2/output/x64/Debug/Gaff.lib ../../../../build/windows/gmake2/output/x64/Debug/Gleam.lib ../../../../build/windows/gmake2/output/x64/Debug/EASTL.lib ../../../../build/windows/gmake2/output/x64/Debug/libpng.lib ../../../../build/windows/gmake2/output/x64/Debug/zlib-ng.lib ../../../../build/windows/gmake2/output/x64/Debug/wxBase64d.lib ../../../../build/windows/gmake2/output/x64/Debug/wxCore64d.lib ../../../../build/windows/gmake2/output/x64/Debug/wxAdv64d.lib ../../../../build/windows/gmake2/output/x64/Debug/ECS.lib -lcomctl32 -lRpcrt4
LDDEPS += ../../../../build/windows/gmake2/output/x64/Debug/EditorBasic.lib ../../../../build/windows/gmake2/output/x64/Debug/Editor.lib ../../../../build/windows/gmake2/output/x64/Debug/Engine.lib ../../../../build/windows/gmake2/output/x64/Debug/Memory64d.lib ../../../../build/windows/gmake2/output/x64/Debug/Gaff.lib ../../../../build/windows/gmake2/output/x64/Debug/Gleam.lib ../../../../build/windows/gmake2/output/x64/Debug/EASTL.lib ../../../../build/windows/gmake2/output/x64/Debug/libpng.lib ../../../../build/windows/gmake2/output/x64/Debug/zlib-ng.lib ../../../../build/windows/gmake2/output/x64/Debug/wxBase64d.lib ../../../../build/windows/gmake2/output/x64/Debug/wxCore64d.lib ../../../../build/windows/gmake2/output/x64/Debug/wxAdv64d.lib ../../../../build/windows/gmake2/output/x64/Debug/ECS.lib
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -shared -Wl,--out-implib="../../../../build/windows/gmake2/output/x64/Debug/EditorBasicModule64d.lib"
define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\EditorModules (mkdir ..\..\..\..\..\workingdir\EditorModules)
	IF EXIST ..\..\..\..\build\windows\gmake2\output\x64\Debug\EditorBasicModule64d.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Debug\EditorBasicModule64d.dll ..\..\..\..\..\workingdir\EditorModules > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Debug\EditorBasicModule64d.dll ..\..\..\..\..\workingdir\EditorModules > nul)
endef
endif

ifeq ($(config),release_x64)
RESCOMP = windres
TARGETDIR = ../../../../build/windows/gmake2/output/x64/Release
TARGET = $(TARGETDIR)/EditorBasicModule64.dll
OBJDIR = ../../../../build/windows/gmake2/intermediate/x64/Release/EditorBasicModule
DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -DNDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DwxUSE_ZLIB_H_IN_PATH -DWXUSINGDLL -D__WXMSW__
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -Werror -ffast-math -O3 -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -Werror -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
LIBS += ../../../../build/windows/gmake2/output/x64/Release/EditorBasic.lib ../../../../build/windows/gmake2/output/x64/Release/Editor.lib ../../../../build/windows/gmake2/output/x64/Release/Engine.lib ../../../../build/windows/gmake2/output/x64/Release/Memory64.lib ../../../../build/windows/gmake2/output/x64/Release/Gaff.lib ../../../../build/windows/gmake2/output/x64/Release/Gleam.lib ../../../../build/windows/gmake2/output/x64/Release/EASTL.lib ../../../../build/windows/gmake2/output/x64/Release/libpng.lib ../../../../build/windows/gmake2/output/x64/Release/zlib-ng.lib ../../../../build/windows/gmake2/output/x64/Release/wxBase64.lib ../../../../build/windows/gmake2/output/x64/Release/wxCore64.lib ../../../../build/windows/gmake2/output/x64/Release/wxAdv64.lib ../../../../build/windows/gmake2/output/x64/Release/ECS.lib -lcomctl32 -lRpcrt4
LDDEPS += ../../../../build/windows/gmake2/output/x64/Release/EditorBasic.lib ../../../../build/windows/gmake2/output/x64/Release/Editor.lib ../../../../build/windows/gmake2/output/x64/Release/Engine.lib ../../../../build/windows/gmake2/output/x64/Release/Memory64.lib ../../../../build/windows/gmake2/output/x64/Release/Gaff.lib ../../../../build/windows/gmake2/output/x64/Release/Gleam.lib ../../../../build/windows/gmake2/output/x64/Release/EASTL.lib ../../../../build/windows/gmake2/output/x64/Release/libpng.lib ../../../../build/windows/gmake2/output/x64/Release/zlib-ng.lib ../../../../build/windows/gmake2/output/x64/Release/wxBase64.lib ../../../../build/windows/gmake2/output/x64/Release/wxCore64.lib ../../../../build/windows/gmake2/output/x64/Release/wxAdv64.lib ../../../../build/windows/gmake2/output/x64/Release/ECS.lib
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake2/output/x64/Release/EditorBasicModule64.lib"
define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\EditorModules (mkdir ..\..\..\..\..\workingdir\EditorModules)
	IF EXIST ..\..\..\..\build\windows\gmake2\output\x64\Release\EditorBasicModule64.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Release\EditorBasicModule64.dll ..\..\..\..\..\workingdir\EditorModules > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Release\EditorBasicModule64.dll ..\..\..\..\..\workingdir\EditorModules > nul)
endef
endif

ifeq ($(config),debug_clang_x64)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
TARGETDIR = ../../../../build/windows/gmake2/output/x64/Debug_Clang
TARGET = $(TARGETDIR)/EditorBasicModule64d.dll
OBJDIR = ../../../../build/windows/gmake2/intermediate/x64/Debug_Clang/EditorBasicModule
DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -D_DEBUG -DDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DwxUSE_ZLIB_H_IN_PATH -DWXUSINGDLL -D__WXMSW__
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Werror -ffast-math -O0 -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Werror -ffast-math -O0 -g -Wall -Wextra -std=c++1z -fno-rtti
LIBS += ../../../../build/windows/gmake2/output/x64/Debug_Clang/EditorBasic.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/Editor.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/Engine.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/Memory64d.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/Gaff.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/Gleam.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/EASTL.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/libpng.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/zlib-ng.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/wxBase64d.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/wxCore64d.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/wxAdv64d.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/ECS.lib -lcomctl32 -lRpcrt4
LDDEPS += ../../../../build/windows/gmake2/output/x64/Debug_Clang/EditorBasic.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/Editor.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/Engine.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/Memory64d.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/Gaff.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/Gleam.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/EASTL.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/libpng.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/zlib-ng.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/wxBase64d.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/wxCore64d.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/wxAdv64d.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/ECS.lib
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -shared -Wl,--out-implib="../../../../build/windows/gmake2/output/x64/Debug_Clang/EditorBasicModule64d.lib"
define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\EditorModules (mkdir ..\..\..\..\..\workingdir\EditorModules)
	IF EXIST ..\..\..\..\build\windows\gmake2\output\x64\Debug_Clang\EditorBasicModule64d.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Debug_Clang\EditorBasicModule64d.dll ..\..\..\..\..\workingdir\EditorModules > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Debug_Clang\EditorBasicModule64d.dll ..\..\..\..\..\workingdir\EditorModules > nul)
endef
endif

ifeq ($(config),release_clang_x64)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
TARGETDIR = ../../../../build/windows/gmake2/output/x64/Release_Clang
TARGET = $(TARGETDIR)/EditorBasicModule64.dll
OBJDIR = ../../../../build/windows/gmake2/intermediate/x64/Release_Clang/EditorBasicModule
DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -DNDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DwxUSE_ZLIB_H_IN_PATH -DWXUSINGDLL -D__WXMSW__
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -Werror -ffast-math -O3 -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -Werror -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
LIBS += ../../../../build/windows/gmake2/output/x64/Release_Clang/EditorBasic.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/Editor.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/Engine.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/Memory64.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/Gaff.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/Gleam.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/EASTL.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/libpng.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/zlib-ng.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/wxBase64.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/wxCore64.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/wxAdv64.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/ECS.lib -lcomctl32 -lRpcrt4
LDDEPS += ../../../../build/windows/gmake2/output/x64/Release_Clang/EditorBasic.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/Editor.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/Engine.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/Memory64.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/Gaff.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/Gleam.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/EASTL.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/libpng.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/zlib-ng.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/wxBase64.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/wxCore64.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/wxAdv64.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/ECS.lib
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake2/output/x64/Release_Clang/EditorBasicModule64.lib"
define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\EditorModules (mkdir ..\..\..\..\..\workingdir\EditorModules)
	IF EXIST ..\..\..\..\build\windows\gmake2\output\x64\Release_Clang\EditorBasicModule64.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Release_Clang\EditorBasicModule64.dll ..\..\..\..\..\workingdir\EditorModules > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Release_Clang\EditorBasicModule64.dll ..\..\..\..\..\workingdir\EditorModules > nul)
endef
endif

ifeq ($(config),profile_x64)
RESCOMP = windres
TARGETDIR = ../../../../build/windows/gmake2/output/x64/Profile
TARGET = $(TARGETDIR)/EditorBasicModule64p.dll
OBJDIR = ../../../../build/windows/gmake2/intermediate/x64/Profile/EditorBasicModule
DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -DNDEBUG -DSHIB_PROFILE -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DwxUSE_ZLIB_H_IN_PATH -DWXUSINGDLL -D__WXMSW__
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -Werror -ffast-math -O3 -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -Werror -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
LIBS += ../../../../build/windows/gmake2/output/x64/Profile/EditorBasic.lib ../../../../build/windows/gmake2/output/x64/Profile/Editor.lib ../../../../build/windows/gmake2/output/x64/Profile/Engine.lib ../../../../build/windows/gmake2/output/x64/Profile/Memory64p.lib ../../../../build/windows/gmake2/output/x64/Profile/Gaff.lib ../../../../build/windows/gmake2/output/x64/Profile/Gleam.lib ../../../../build/windows/gmake2/output/x64/Profile/EASTL.lib ../../../../build/windows/gmake2/output/x64/Profile/libpng.lib ../../../../build/windows/gmake2/output/x64/Profile/zlib-ng.lib ../../../../build/windows/gmake2/output/x64/Profile/wxBase64p.lib ../../../../build/windows/gmake2/output/x64/Profile/wxCore64p.lib ../../../../build/windows/gmake2/output/x64/Profile/wxAdv64p.lib ../../../../build/windows/gmake2/output/x64/Profile/ECS.lib -lcomctl32 -lRpcrt4
LDDEPS += ../../../../build/windows/gmake2/output/x64/Profile/EditorBasic.lib ../../../../build/windows/gmake2/output/x64/Profile/Editor.lib ../../../../build/windows/gmake2/output/x64/Profile/Engine.lib ../../../../build/windows/gmake2/output/x64/Profile/Memory64p.lib ../../../../build/windows/gmake2/output/x64/Profile/Gaff.lib ../../../../build/windows/gmake2/output/x64/Profile/Gleam.lib ../../../../build/windows/gmake2/output/x64/Profile/EASTL.lib ../../../../build/windows/gmake2/output/x64/Profile/libpng.lib ../../../../build/windows/gmake2/output/x64/Profile/zlib-ng.lib ../../../../build/windows/gmake2/output/x64/Profile/wxBase64p.lib ../../../../build/windows/gmake2/output/x64/Profile/wxCore64p.lib ../../../../build/windows/gmake2/output/x64/Profile/wxAdv64p.lib ../../../../build/windows/gmake2/output/x64/Profile/ECS.lib
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake2/output/x64/Profile/EditorBasicModule64p.lib"
define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\EditorModules (mkdir ..\..\..\..\..\workingdir\EditorModules)
	IF EXIST ..\..\..\..\build\windows\gmake2\output\x64\Profile\EditorBasicModule64p.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Profile\EditorBasicModule64p.dll ..\..\..\..\..\workingdir\EditorModules > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Profile\EditorBasicModule64p.dll ..\..\..\..\..\workingdir\EditorModules > nul)
endef
endif

ifeq ($(config),profile_clang_x64)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
TARGETDIR = ../../../../build/windows/gmake2/output/x64/Profile_Clang
TARGET = $(TARGETDIR)/EditorBasicModule64p.dll
OBJDIR = ../../../../build/windows/gmake2/intermediate/x64/Profile_Clang/EditorBasicModule
DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -DNDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DwxUSE_ZLIB_H_IN_PATH -DWXUSINGDLL -D__WXMSW__
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -Werror -ffast-math -O3 -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -Werror -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
LIBS += ../../../../build/windows/gmake2/output/x64/Profile_Clang/EditorBasic.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/Editor.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/Engine.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/Memory64p.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/Gaff.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/Gleam.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/EASTL.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/libpng.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/zlib-ng.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/wxBase64p.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/wxCore64p.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/wxAdv64p.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/ECS.lib -lcomctl32 -lRpcrt4
LDDEPS += ../../../../build/windows/gmake2/output/x64/Profile_Clang/EditorBasic.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/Editor.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/Engine.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/Memory64p.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/Gaff.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/Gleam.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/EASTL.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/libpng.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/zlib-ng.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/wxBase64p.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/wxCore64p.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/wxAdv64p.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/ECS.lib
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake2/output/x64/Profile_Clang/EditorBasicModule64p.lib"
define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\EditorModules (mkdir ..\..\..\..\..\workingdir\EditorModules)
	IF EXIST ..\..\..\..\build\windows\gmake2\output\x64\Profile_Clang\EditorBasicModule64p.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Profile_Clang\EditorBasicModule64p.dll ..\..\..\..\..\workingdir\EditorModules > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Profile_Clang\EditorBasicModule64p.dll ..\..\..\..\..\workingdir\EditorModules > nul)
endef
endif

ifeq ($(config),optimized_debug_x64)
RESCOMP = windres
TARGETDIR = ../../../../build/windows/gmake2/output/x64/Optimized_Debug
TARGET = $(TARGETDIR)/EditorBasicModule64od.dll
OBJDIR = ../../../../build/windows/gmake2/intermediate/x64/Optimized_Debug/EditorBasicModule
DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -D_DEBUG -DDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DwxUSE_ZLIB_H_IN_PATH -DWXUSINGDLL -D__WXMSW__
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -Werror -ffast-math -O3 -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -Werror -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
LIBS += ../../../../build/windows/gmake2/output/x64/Optimized_Debug/EditorBasic.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/Editor.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/Engine.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/Memory64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/Gaff.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/Gleam.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/EASTL.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/libpng.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/zlib-ng.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/wxBase64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/wxCore64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/wxAdv64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/ECS.lib -lcomctl32 -lRpcrt4
LDDEPS += ../../../../build/windows/gmake2/output/x64/Optimized_Debug/EditorBasic.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/Editor.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/Engine.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/Memory64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/Gaff.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/Gleam.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/EASTL.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/libpng.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/zlib-ng.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/wxBase64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/wxCore64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/wxAdv64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/ECS.lib
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake2/output/x64/Optimized_Debug/EditorBasicModule64od.lib"
define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\EditorModules (mkdir ..\..\..\..\..\workingdir\EditorModules)
	IF EXIST ..\..\..\..\build\windows\gmake2\output\x64\Optimized_Debug\EditorBasicModule64od.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Optimized_Debug\EditorBasicModule64od.dll ..\..\..\..\..\workingdir\EditorModules > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Optimized_Debug\EditorBasicModule64od.dll ..\..\..\..\..\workingdir\EditorModules > nul)
endef
endif

ifeq ($(config),optimized_debug_clang_x64)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
TARGETDIR = ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang
TARGET = $(TARGETDIR)/EditorBasicModule64od.dll
OBJDIR = ../../../../build/windows/gmake2/intermediate/x64/Optimized_Debug_Clang/EditorBasicModule
DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -D_DEBUG -DDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DwxUSE_ZLIB_H_IN_PATH -DWXUSINGDLL -D__WXMSW__
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -Werror -ffast-math -O3 -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -Werror -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
LIBS += ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/EditorBasic.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/Editor.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/Engine.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/Memory64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/Gaff.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/Gleam.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/EASTL.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/libpng.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/zlib-ng.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/wxBase64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/wxCore64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/wxAdv64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/ECS.lib -lcomctl32 -lRpcrt4
LDDEPS += ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/EditorBasic.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/Editor.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/Engine.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/Memory64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/Gaff.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/Gleam.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/EASTL.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/libpng.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/zlib-ng.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/wxBase64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/wxCore64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/wxAdv64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/ECS.lib
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/EditorBasicModule64od.lib"
define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\EditorModules (mkdir ..\..\..\..\..\workingdir\EditorModules)
	IF EXIST ..\..\..\..\build\windows\gmake2\output\x64\Optimized_Debug_Clang\EditorBasicModule64od.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Optimized_Debug_Clang\EditorBasicModule64od.dll ..\..\..\..\..\workingdir\EditorModules > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Optimized_Debug_Clang\EditorBasicModule64od.dll ..\..\..\..\..\workingdir\EditorModules > nul)
endef
endif

# Per File Configurations
# #############################################


# File sets
# #############################################

OBJECTS :=

OBJECTS += $(OBJDIR)/Shibboleth_EditorBasicModule.o

# Rules
# #############################################

all: prebuild prelink $(TARGET) | $(TARGETDIR) $(OBJDIR)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	@echo Linking EditorBasicModule
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning EditorBasicModule
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH) | $(OBJDIR) $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
	$(SILENT) touch "$@"
else
$(OBJECTS): | $(OBJDIR)
endif


# File Rules
# #############################################

$(OBJDIR)/Shibboleth_EditorBasicModule.o: ../../../../../src/Modules/EditorBasic/Shibboleth_EditorBasicModule.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include "$(PCH_PLACEHOLDER).d"
endif