# GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),debug_x64)
  RESCOMP = windres
  TARGETDIR = ../../../../build/windows/gmake/output/x64/Debug
  TARGET = $(TARGETDIR)/wxPropGrid64d.dll
  OBJDIR = ../../../../build/windows/gmake/intermediate/x64/Debug/wxPropGrid
  DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -D_DEBUG -DDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DWXBUILDING -DwxUSE_ZLIB_H_IN_PATH -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NON_CONFORMING_SWPRINTFS=1 -D_SCL_SECURE_NO_WARNINGS=1 -DXML_STATIC -DWXMAKINGDLL_PROPGRID -DWXUSINGDLL -D__WXMSW__
  INCLUDES += -I../../../../../src/Dependencies/wxWidgets/include -I../../../../../src/Dependencies/wxWidgets/include/msvc
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -ffast-math -Og -g -Wall -Wextra
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -ffast-math -Og -g -Wall -Wextra -std=c++1z -fno-rtti
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../build/windows/gmake/output/x64/Debug/Engine.lib ../../../../build/windows/gmake/output/x64/Debug/Memory64d.lib ../../../../build/windows/gmake/output/x64/Debug/wxBase64d.lib ../../../../build/windows/gmake/output/x64/Debug/wxCore64d.lib ../../../../build/windows/gmake/output/x64/Debug/wxAdv64d.lib
  LDDEPS += ../../../../build/windows/gmake/output/x64/Debug/Engine.lib ../../../../build/windows/gmake/output/x64/Debug/Memory64d.lib ../../../../build/windows/gmake/output/x64/Debug/wxBase64d.lib ../../../../build/windows/gmake/output/x64/Debug/wxCore64d.lib ../../../../build/windows/gmake/output/x64/Debug/wxAdv64d.lib
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -shared -Wl,--out-implib="../../../../build/windows/gmake/output/x64/Debug/wxPropGrid64d.lib"
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\bin (mkdir ..\..\..\..\..\workingdir\bin)
	IF EXIST ..\..\..\..\build\windows\gmake\output\x64\Debug\wxPropGrid64d.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake\output\x64\Debug\wxPropGrid64d.dll ..\..\..\..\..\workingdir\bin > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake\output\x64\Debug\wxPropGrid64d.dll ..\..\..\..\..\workingdir\bin > nul)
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_x64)
  RESCOMP = windres
  TARGETDIR = ../../../../build/windows/gmake/output/x64/Release
  TARGET = $(TARGETDIR)/wxPropGrid64.dll
  OBJDIR = ../../../../build/windows/gmake/intermediate/x64/Release/wxPropGrid
  DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -DNDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DWXBUILDING -DwxUSE_ZLIB_H_IN_PATH -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NON_CONFORMING_SWPRINTFS=1 -D_SCL_SECURE_NO_WARNINGS=1 -DXML_STATIC -DWXMAKINGDLL_PROPGRID -DWXUSINGDLL -D__WXMSW__
  INCLUDES += -I../../../../../src/Dependencies/wxWidgets/include -I../../../../../src/Dependencies/wxWidgets/include/msvc
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../build/windows/gmake/output/x64/Release/Engine.lib ../../../../build/windows/gmake/output/x64/Release/Memory64.lib ../../../../build/windows/gmake/output/x64/Release/wxBase64.lib ../../../../build/windows/gmake/output/x64/Release/wxCore64.lib ../../../../build/windows/gmake/output/x64/Release/wxAdv64.lib
  LDDEPS += ../../../../build/windows/gmake/output/x64/Release/Engine.lib ../../../../build/windows/gmake/output/x64/Release/Memory64.lib ../../../../build/windows/gmake/output/x64/Release/wxBase64.lib ../../../../build/windows/gmake/output/x64/Release/wxCore64.lib ../../../../build/windows/gmake/output/x64/Release/wxAdv64.lib
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake/output/x64/Release/wxPropGrid64.lib"
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\bin (mkdir ..\..\..\..\..\workingdir\bin)
	IF EXIST ..\..\..\..\build\windows\gmake\output\x64\Release\wxPropGrid64.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake\output\x64\Release\wxPropGrid64.dll ..\..\..\..\..\workingdir\bin > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake\output\x64\Release\wxPropGrid64.dll ..\..\..\..\..\workingdir\bin > nul)
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),debug_clang_x64)
  ifeq ($(origin CC), default)
    CC = clang
  endif
  ifeq ($(origin CXX), default)
    CXX = clang++
  endif
  ifeq ($(origin AR), default)
    AR = ar
  endif
  TARGETDIR = ../../../../build/windows/gmake/output/x64/Debug_Clang
  TARGET = $(TARGETDIR)/wxPropGrid64d.dll
  OBJDIR = ../../../../build/windows/gmake/intermediate/x64/Debug_Clang/wxPropGrid
  DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -D_DEBUG -DDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DWXBUILDING -DwxUSE_ZLIB_H_IN_PATH -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NON_CONFORMING_SWPRINTFS=1 -D_SCL_SECURE_NO_WARNINGS=1 -DXML_STATIC -DWXMAKINGDLL_PROPGRID -DWXUSINGDLL -D__WXMSW__
  INCLUDES += -I../../../../../src/Dependencies/wxWidgets/include -I../../../../../src/Dependencies/wxWidgets/include/msvc
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -ffast-math -O0 -g -Wall -Wextra
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -ffast-math -O0 -g -Wall -Wextra -std=c++1z -fno-rtti
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../build/windows/gmake/output/x64/Debug_Clang/Engine.lib ../../../../build/windows/gmake/output/x64/Debug_Clang/Memory64d.lib ../../../../build/windows/gmake/output/x64/Debug_Clang/wxBase64d.lib ../../../../build/windows/gmake/output/x64/Debug_Clang/wxCore64d.lib ../../../../build/windows/gmake/output/x64/Debug_Clang/wxAdv64d.lib
  LDDEPS += ../../../../build/windows/gmake/output/x64/Debug_Clang/Engine.lib ../../../../build/windows/gmake/output/x64/Debug_Clang/Memory64d.lib ../../../../build/windows/gmake/output/x64/Debug_Clang/wxBase64d.lib ../../../../build/windows/gmake/output/x64/Debug_Clang/wxCore64d.lib ../../../../build/windows/gmake/output/x64/Debug_Clang/wxAdv64d.lib
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -shared -Wl,--out-implib="../../../../build/windows/gmake/output/x64/Debug_Clang/wxPropGrid64d.lib"
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\bin (mkdir ..\..\..\..\..\workingdir\bin)
	IF EXIST ..\..\..\..\build\windows\gmake\output\x64\Debug_Clang\wxPropGrid64d.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake\output\x64\Debug_Clang\wxPropGrid64d.dll ..\..\..\..\..\workingdir\bin > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake\output\x64\Debug_Clang\wxPropGrid64d.dll ..\..\..\..\..\workingdir\bin > nul)
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_clang_x64)
  ifeq ($(origin CC), default)
    CC = clang
  endif
  ifeq ($(origin CXX), default)
    CXX = clang++
  endif
  ifeq ($(origin AR), default)
    AR = ar
  endif
  TARGETDIR = ../../../../build/windows/gmake/output/x64/Release_Clang
  TARGET = $(TARGETDIR)/wxPropGrid64.dll
  OBJDIR = ../../../../build/windows/gmake/intermediate/x64/Release_Clang/wxPropGrid
  DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -DNDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DWXBUILDING -DwxUSE_ZLIB_H_IN_PATH -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NON_CONFORMING_SWPRINTFS=1 -D_SCL_SECURE_NO_WARNINGS=1 -DXML_STATIC -DWXMAKINGDLL_PROPGRID -DWXUSINGDLL -D__WXMSW__
  INCLUDES += -I../../../../../src/Dependencies/wxWidgets/include -I../../../../../src/Dependencies/wxWidgets/include/msvc
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../build/windows/gmake/output/x64/Release_Clang/Engine.lib ../../../../build/windows/gmake/output/x64/Release_Clang/Memory64.lib ../../../../build/windows/gmake/output/x64/Release_Clang/wxBase64.lib ../../../../build/windows/gmake/output/x64/Release_Clang/wxCore64.lib ../../../../build/windows/gmake/output/x64/Release_Clang/wxAdv64.lib
  LDDEPS += ../../../../build/windows/gmake/output/x64/Release_Clang/Engine.lib ../../../../build/windows/gmake/output/x64/Release_Clang/Memory64.lib ../../../../build/windows/gmake/output/x64/Release_Clang/wxBase64.lib ../../../../build/windows/gmake/output/x64/Release_Clang/wxCore64.lib ../../../../build/windows/gmake/output/x64/Release_Clang/wxAdv64.lib
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake/output/x64/Release_Clang/wxPropGrid64.lib"
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\bin (mkdir ..\..\..\..\..\workingdir\bin)
	IF EXIST ..\..\..\..\build\windows\gmake\output\x64\Release_Clang\wxPropGrid64.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake\output\x64\Release_Clang\wxPropGrid64.dll ..\..\..\..\..\workingdir\bin > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake\output\x64\Release_Clang\wxPropGrid64.dll ..\..\..\..\..\workingdir\bin > nul)
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),profile_x64)
  RESCOMP = windres
  TARGETDIR = ../../../../build/windows/gmake/output/x64/Profile
  TARGET = $(TARGETDIR)/wxPropGrid64p.dll
  OBJDIR = ../../../../build/windows/gmake/intermediate/x64/Profile/wxPropGrid
  DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -DNDEBUG -DSHIB_PROFILE -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DWXBUILDING -DwxUSE_ZLIB_H_IN_PATH -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NON_CONFORMING_SWPRINTFS=1 -D_SCL_SECURE_NO_WARNINGS=1 -DXML_STATIC -DWXMAKINGDLL_PROPGRID -DWXUSINGDLL -D__WXMSW__
  INCLUDES += -I../../../../../src/Dependencies/wxWidgets/include -I../../../../../src/Dependencies/wxWidgets/include/msvc
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../build/windows/gmake/output/x64/Profile/Engine.lib ../../../../build/windows/gmake/output/x64/Profile/Memory64p.lib ../../../../build/windows/gmake/output/x64/Profile/wxBase64p.lib ../../../../build/windows/gmake/output/x64/Profile/wxCore64p.lib ../../../../build/windows/gmake/output/x64/Profile/wxAdv64p.lib
  LDDEPS += ../../../../build/windows/gmake/output/x64/Profile/Engine.lib ../../../../build/windows/gmake/output/x64/Profile/Memory64p.lib ../../../../build/windows/gmake/output/x64/Profile/wxBase64p.lib ../../../../build/windows/gmake/output/x64/Profile/wxCore64p.lib ../../../../build/windows/gmake/output/x64/Profile/wxAdv64p.lib
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake/output/x64/Profile/wxPropGrid64p.lib"
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\bin (mkdir ..\..\..\..\..\workingdir\bin)
	IF EXIST ..\..\..\..\build\windows\gmake\output\x64\Profile\wxPropGrid64p.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake\output\x64\Profile\wxPropGrid64p.dll ..\..\..\..\..\workingdir\bin > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake\output\x64\Profile\wxPropGrid64p.dll ..\..\..\..\..\workingdir\bin > nul)
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),profile_clang_x64)
  ifeq ($(origin CC), default)
    CC = clang
  endif
  ifeq ($(origin CXX), default)
    CXX = clang++
  endif
  ifeq ($(origin AR), default)
    AR = ar
  endif
  TARGETDIR = ../../../../build/windows/gmake/output/x64/Profile_Clang
  TARGET = $(TARGETDIR)/wxPropGrid64p.dll
  OBJDIR = ../../../../build/windows/gmake/intermediate/x64/Profile_Clang/wxPropGrid
  DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -DNDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DWXBUILDING -DwxUSE_ZLIB_H_IN_PATH -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NON_CONFORMING_SWPRINTFS=1 -D_SCL_SECURE_NO_WARNINGS=1 -DXML_STATIC -DWXMAKINGDLL_PROPGRID -DWXUSINGDLL -D__WXMSW__
  INCLUDES += -I../../../../../src/Dependencies/wxWidgets/include -I../../../../../src/Dependencies/wxWidgets/include/msvc
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../build/windows/gmake/output/x64/Profile_Clang/Engine.lib ../../../../build/windows/gmake/output/x64/Profile_Clang/Memory64p.lib ../../../../build/windows/gmake/output/x64/Profile_Clang/wxBase64p.lib ../../../../build/windows/gmake/output/x64/Profile_Clang/wxCore64p.lib ../../../../build/windows/gmake/output/x64/Profile_Clang/wxAdv64p.lib
  LDDEPS += ../../../../build/windows/gmake/output/x64/Profile_Clang/Engine.lib ../../../../build/windows/gmake/output/x64/Profile_Clang/Memory64p.lib ../../../../build/windows/gmake/output/x64/Profile_Clang/wxBase64p.lib ../../../../build/windows/gmake/output/x64/Profile_Clang/wxCore64p.lib ../../../../build/windows/gmake/output/x64/Profile_Clang/wxAdv64p.lib
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake/output/x64/Profile_Clang/wxPropGrid64p.lib"
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\bin (mkdir ..\..\..\..\..\workingdir\bin)
	IF EXIST ..\..\..\..\build\windows\gmake\output\x64\Profile_Clang\wxPropGrid64p.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake\output\x64\Profile_Clang\wxPropGrid64p.dll ..\..\..\..\..\workingdir\bin > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake\output\x64\Profile_Clang\wxPropGrid64p.dll ..\..\..\..\..\workingdir\bin > nul)
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),optimized_debug_x64)
  RESCOMP = windres
  TARGETDIR = ../../../../build/windows/gmake/output/x64/Optimized_Debug
  TARGET = $(TARGETDIR)/wxPropGrid64od.dll
  OBJDIR = ../../../../build/windows/gmake/intermediate/x64/Optimized_Debug/wxPropGrid
  DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -D_DEBUG -DDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DWXBUILDING -DwxUSE_ZLIB_H_IN_PATH -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NON_CONFORMING_SWPRINTFS=1 -D_SCL_SECURE_NO_WARNINGS=1 -DXML_STATIC -DWXMAKINGDLL_PROPGRID -DWXUSINGDLL -D__WXMSW__
  INCLUDES += -I../../../../../src/Dependencies/wxWidgets/include -I../../../../../src/Dependencies/wxWidgets/include/msvc
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../build/windows/gmake/output/x64/Optimized_Debug/Engine.lib ../../../../build/windows/gmake/output/x64/Optimized_Debug/Memory64od.lib ../../../../build/windows/gmake/output/x64/Optimized_Debug/wxBase64od.lib ../../../../build/windows/gmake/output/x64/Optimized_Debug/wxCore64od.lib ../../../../build/windows/gmake/output/x64/Optimized_Debug/wxAdv64od.lib
  LDDEPS += ../../../../build/windows/gmake/output/x64/Optimized_Debug/Engine.lib ../../../../build/windows/gmake/output/x64/Optimized_Debug/Memory64od.lib ../../../../build/windows/gmake/output/x64/Optimized_Debug/wxBase64od.lib ../../../../build/windows/gmake/output/x64/Optimized_Debug/wxCore64od.lib ../../../../build/windows/gmake/output/x64/Optimized_Debug/wxAdv64od.lib
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake/output/x64/Optimized_Debug/wxPropGrid64od.lib"
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\bin (mkdir ..\..\..\..\..\workingdir\bin)
	IF EXIST ..\..\..\..\build\windows\gmake\output\x64\Optimized_Debug\wxPropGrid64od.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake\output\x64\Optimized_Debug\wxPropGrid64od.dll ..\..\..\..\..\workingdir\bin > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake\output\x64\Optimized_Debug\wxPropGrid64od.dll ..\..\..\..\..\workingdir\bin > nul)
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),optimized_debug_clang_x64)
  ifeq ($(origin CC), default)
    CC = clang
  endif
  ifeq ($(origin CXX), default)
    CXX = clang++
  endif
  ifeq ($(origin AR), default)
    AR = ar
  endif
  TARGETDIR = ../../../../build/windows/gmake/output/x64/Optimized_Debug_Clang
  TARGET = $(TARGETDIR)/wxPropGrid64od.dll
  OBJDIR = ../../../../build/windows/gmake/intermediate/x64/Optimized_Debug_Clang/wxPropGrid
  DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -D_DEBUG -DDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DWXBUILDING -DwxUSE_ZLIB_H_IN_PATH -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NON_CONFORMING_SWPRINTFS=1 -D_SCL_SECURE_NO_WARNINGS=1 -DXML_STATIC -DWXMAKINGDLL_PROPGRID -DWXUSINGDLL -D__WXMSW__
  INCLUDES += -I../../../../../src/Dependencies/wxWidgets/include -I../../../../../src/Dependencies/wxWidgets/include/msvc
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../../build/windows/gmake/output/x64/Optimized_Debug_Clang/Engine.lib ../../../../build/windows/gmake/output/x64/Optimized_Debug_Clang/Memory64od.lib ../../../../build/windows/gmake/output/x64/Optimized_Debug_Clang/wxBase64od.lib ../../../../build/windows/gmake/output/x64/Optimized_Debug_Clang/wxCore64od.lib ../../../../build/windows/gmake/output/x64/Optimized_Debug_Clang/wxAdv64od.lib
  LDDEPS += ../../../../build/windows/gmake/output/x64/Optimized_Debug_Clang/Engine.lib ../../../../build/windows/gmake/output/x64/Optimized_Debug_Clang/Memory64od.lib ../../../../build/windows/gmake/output/x64/Optimized_Debug_Clang/wxBase64od.lib ../../../../build/windows/gmake/output/x64/Optimized_Debug_Clang/wxCore64od.lib ../../../../build/windows/gmake/output/x64/Optimized_Debug_Clang/wxAdv64od.lib
  ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake/output/x64/Optimized_Debug_Clang/wxPropGrid64od.lib"
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\bin (mkdir ..\..\..\..\..\workingdir\bin)
	IF EXIST ..\..\..\..\build\windows\gmake\output\x64\Optimized_Debug_Clang\wxPropGrid64od.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake\output\x64\Optimized_Debug_Clang\wxPropGrid64od.dll ..\..\..\..\..\workingdir\bin > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake\output\x64\Optimized_Debug_Clang\wxPropGrid64od.dll ..\..\..\..\..\workingdir\bin > nul)
  endef
all: prebuild prelink $(TARGET)
	@:

endif

OBJECTS := \
	$(OBJDIR)/dummy.o \
	$(OBJDIR)/advprops.o \
	$(OBJDIR)/editors.o \
	$(OBJDIR)/manager.o \
	$(OBJDIR)/property.o \
	$(OBJDIR)/propgrid.o \
	$(OBJDIR)/propgridiface.o \
	$(OBJDIR)/propgridpagestate.o \
	$(OBJDIR)/props.o \

RESOURCES := \

CUSTOMFILES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

$(TARGET): $(GCH) ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking wxPropGrid
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

clean:
	@echo Cleaning wxPropGrid
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH)
$(GCH): $(PCH)
	@echo $(notdir $<)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
endif

$(OBJDIR)/dummy.o: ../../../../../src/Dependencies/wxWidgets/src/common/dummy.cpp
	@echo $(notdir $<)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/advprops.o: ../../../../../src/Dependencies/wxWidgets/src/propgrid/advprops.cpp
	@echo $(notdir $<)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/editors.o: ../../../../../src/Dependencies/wxWidgets/src/propgrid/editors.cpp
	@echo $(notdir $<)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/manager.o: ../../../../../src/Dependencies/wxWidgets/src/propgrid/manager.cpp
	@echo $(notdir $<)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/property.o: ../../../../../src/Dependencies/wxWidgets/src/propgrid/property.cpp
	@echo $(notdir $<)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/propgrid.o: ../../../../../src/Dependencies/wxWidgets/src/propgrid/propgrid.cpp
	@echo $(notdir $<)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/propgridiface.o: ../../../../../src/Dependencies/wxWidgets/src/propgrid/propgridiface.cpp
	@echo $(notdir $<)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/propgridpagestate.o: ../../../../../src/Dependencies/wxWidgets/src/propgrid/propgridpagestate.cpp
	@echo $(notdir $<)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/props.o: ../../../../../src/Dependencies/wxWidgets/src/propgrid/props.cpp
	@echo $(notdir $<)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif