/************************************************************************************
Copyright (C) 2020 by Nicholas LaCroix

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
************************************************************************************/

#include "Shibboleth_InputReflection.h"

SHIB_REFLECTION_DEFINE_BEGIN(Gleam::MouseCode)
	.entry("Mouse Button Left", Gleam::MouseCode::Left)
	.entry("Mouse Button Right", Gleam::MouseCode::Right)
	.entry("Mouse Button Middle", Gleam::MouseCode::Middle)
	.entry("Mouse Button Back", Gleam::MouseCode::Back)
	.entry("Mouse Button Forward", Gleam::MouseCode::Forward)
	.entry("Mouse Button 5", Gleam::MouseCode::Button5)
	.entry("Mouse Button 6", Gleam::MouseCode::Button6)
	.entry("Mouse Button 7", Gleam::MouseCode::Button7)
	.entry("Mouse Wheel Vertical", Gleam::MouseCode::WheelVertical)
	.entry("Mouse Wheel Up", Gleam::MouseCode::WheelUp)
	.entry("Mouse Wheel Down", Gleam::MouseCode::WheelDown)
	.entry("Mouse Wheel Horizontal", Gleam::MouseCode::WheelHorizontal)
	.entry("Mouse Wheel Lefft", Gleam::MouseCode::WheelLeft)
	.entry("Mouse Wheel Right", Gleam::MouseCode::WheelRight)

	.entry("Mouse Delta X", Gleam::MouseCode::DeltaX)
	.entry("Mouse Delta Y", Gleam::MouseCode::DeltaY)
	.entry("Mouse Position X", Gleam::MouseCode::PosX)
	.entry("Mouse Position Y", Gleam::MouseCode::PosY)
	SHIB_REFLECTION_DEFINE_END(Gleam::MouseCode)

SHIB_REFLECTION_DEFINE_BEGIN(Gleam::KeyCode)
	.entry("Backspace", Gleam::KeyCode::Backspace)
	.entry("Tab", Gleam::KeyCode::Tab)
	.entry("Enter", Gleam::KeyCode::Enter)
	.entry("Pause", Gleam::KeyCode::Pause)
	.entry("Capslock", Gleam::KeyCode::CapsLock)
	.entry("Escape", Gleam::KeyCode::Escape)
	.entry("Space", Gleam::KeyCode::Space)
	.entry("Page Up", Gleam::KeyCode::PageUp)
	.entry("Page Down", Gleam::KeyCode::PageDown)
	.entry("End", Gleam::KeyCode::End)
	.entry("Home", Gleam::KeyCode::Home)
	.entry("Left", Gleam::KeyCode::Left)
	.entry("Right", Gleam::KeyCode::Right)
	.entry("Up", Gleam::KeyCode::Up)
	.entry("Down", Gleam::KeyCode::Down)
	.entry("Print Screen", Gleam::KeyCode::PrintScreen)
	.entry("Insert", Gleam::KeyCode::Insert)
	.entry("Delete", Gleam::KeyCode::Delete)
	.entry("0", Gleam::KeyCode::Num0)
	.entry("1", Gleam::KeyCode::Num1)
	.entry("2", Gleam::KeyCode::Num2)
	.entry("3", Gleam::KeyCode::Num3)
	.entry("4", Gleam::KeyCode::Num4)
	.entry("5", Gleam::KeyCode::Num5)
	.entry("6", Gleam::KeyCode::Num6)
	.entry("7", Gleam::KeyCode::Num7)
	.entry("8", Gleam::KeyCode::Num8)
	.entry("9", Gleam::KeyCode::Num9)
	.entry("A", Gleam::KeyCode::A)
	.entry("B", Gleam::KeyCode::B)
	.entry("C", Gleam::KeyCode::C)
	.entry("D", Gleam::KeyCode::D)
	.entry("E", Gleam::KeyCode::E)
	.entry("F", Gleam::KeyCode::F)
	.entry("G", Gleam::KeyCode::G)
	.entry("H", Gleam::KeyCode::H)
	.entry("I", Gleam::KeyCode::I)
	.entry("J", Gleam::KeyCode::J)
	.entry("K", Gleam::KeyCode::K)
	.entry("L", Gleam::KeyCode::L)
	.entry("M", Gleam::KeyCode::M)
	.entry("N", Gleam::KeyCode::N)
	.entry("O", Gleam::KeyCode::O)
	.entry("P", Gleam::KeyCode::P)
	.entry("Q", Gleam::KeyCode::Q)
	.entry("R", Gleam::KeyCode::R)
	.entry("S", Gleam::KeyCode::S)
	.entry("T", Gleam::KeyCode::T)
	.entry("U", Gleam::KeyCode::U)
	.entry("V", Gleam::KeyCode::V)
	.entry("W", Gleam::KeyCode::W)
	.entry("X", Gleam::KeyCode::X)
	.entry("y", Gleam::KeyCode::Y)
	.entry("Z", Gleam::KeyCode::Z)
	.entry("Left Super", Gleam::KeyCode::LeftSuper)
	.entry("Right Super", Gleam::KeyCode::RightSuper)
	.entry("Numpad 0", Gleam::KeyCode::Numpad0)
	.entry("Numpad 1", Gleam::KeyCode::Numpad1)
	.entry("Numpad 2", Gleam::KeyCode::Numpad2)
	.entry("Numpad 3", Gleam::KeyCode::Numpad3)
	.entry("Numpad 4", Gleam::KeyCode::Numpad4)
	.entry("Numpad 5", Gleam::KeyCode::Numpad5)
	.entry("Numpad 6", Gleam::KeyCode::Numpad6)
	.entry("Numpad 7", Gleam::KeyCode::Numpad7)
	.entry("Numpad 8", Gleam::KeyCode::Numpad8)
	.entry("Numpad 9", Gleam::KeyCode::Numpad9)
	.entry("Numpad *", Gleam::KeyCode::Multiply)
	.entry("Numpad +", Gleam::KeyCode::Add)
	.entry("Numpad -", Gleam::KeyCode::Subtract)
	.entry("Numpad .", Gleam::KeyCode::Decimal)
	.entry("Numpad /", Gleam::KeyCode::Divide)
	.entry("Numpad Enter", Gleam::KeyCode::NumpadEnter)
	.entry("F1", Gleam::KeyCode::F1)
	.entry("F2", Gleam::KeyCode::F2)
	.entry("F3", Gleam::KeyCode::F3)
	.entry("F4", Gleam::KeyCode::F4)
	.entry("F5", Gleam::KeyCode::F5)
	.entry("F6", Gleam::KeyCode::F6)
	.entry("F7", Gleam::KeyCode::F7)
	.entry("F8", Gleam::KeyCode::F8)
	.entry("F9", Gleam::KeyCode::F9)
	.entry("F10", Gleam::KeyCode::F10)
	.entry("F11", Gleam::KeyCode::F11)
	.entry("F12", Gleam::KeyCode::F12)
	.entry("Numlock", Gleam::KeyCode::NumLock)
	.entry("Scrolllock", Gleam::KeyCode::ScrollLock)
	.entry("Left Shift", Gleam::KeyCode::LeftShift)
	.entry("Right Shift", Gleam::KeyCode::RightShift)
	.entry("Left Control", Gleam::KeyCode::LeftControl)
	.entry("Right Control", Gleam::KeyCode::RightControl)
	.entry("Left Alt", Gleam::KeyCode::LeftAlt)
	.entry("Right Alt", Gleam::KeyCode::RightAlt)
	.entry(";", Gleam::KeyCode::Semicolon)
	.entry("=", Gleam::KeyCode::Equals)
	.entry(",", Gleam::KeyCode::Comma)
	.entry(".", Gleam::KeyCode::Period)
	.entry("/", Gleam::KeyCode::ForwardSlash)
	.entry("\\", Gleam::KeyCode::Backslash)
	.entry("`", Gleam::KeyCode::Tilde)
	.entry("[", Gleam::KeyCode::LeftSquareBracket)
	.entry("]", Gleam::KeyCode::RightSquareBracket)
	.entry("'", Gleam::KeyCode::Apostrophe)
SHIB_REFLECTION_DEFINE_END(Gleam::KeyCode)
