files
{
	"include/wx/propgrid/advprops.h",
	"include/wx/propgrid/editors.h",
	"include/wx/propgrid/manager.h",
	"include/wx/propgrid/property.h",
	"include/wx/propgrid/propgrid.h",
	"include/wx/propgrid/propgriddefs.h",
	"include/wx/propgrid/propgridiface.h",
	"include/wx/propgrid/propgridpagestate.h",
	"include/wx/propgrid/props.h",
	"src/common/dummy.cpp",
	"src/propgrid/advprops.cpp",
	"src/propgrid/editors.cpp",
	"src/propgrid/manager.cpp",
	"src/propgrid/property.cpp",
	"src/propgrid/propgrid.cpp",
	"src/propgrid/propgridiface.cpp",
	"src/propgrid/propgridpagestate.cpp",
	"src/propgrid/props.cpp"
}
