# Alternative GNU Make project makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

# Configurations
# #############################################

INCLUDES += -I../../../../../src/Dependencies/wxWidgets/include -I../../../../../src/Dependencies/wxWidgets/include/msvc
FORCE_INCLUDE +=
ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
define PREBUILDCMDS
endef
define PRELINKCMDS
endef

ifeq ($(config),debug_x64)
RESCOMP = windres
TARGETDIR = ../../../../build/windows/gmake2/output/x64/Debug
TARGET = $(TARGETDIR)/wxMedia64d.dll
OBJDIR = ../../../../build/windows/gmake2/intermediate/x64/Debug/wxMedia
DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -D_DEBUG -DDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DWXBUILDING -DwxUSE_ZLIB_H_IN_PATH -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NON_CONFORMING_SWPRINTFS=1 -D_SCL_SECURE_NO_WARNINGS=1 -DXML_STATIC -DWXMAKINGDLL_MEDIA -DWXUSINGDLL -D__WXMSW__
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -ffast-math -Og -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -ffast-math -Og -g -Wall -Wextra -std=c++1z -fno-rtti
LIBS += ../../../../build/windows/gmake2/output/x64/Debug/Engine.lib ../../../../build/windows/gmake2/output/x64/Debug/Memory64d.lib ../../../../build/windows/gmake2/output/x64/Debug/wxBase64d.lib ../../../../build/windows/gmake2/output/x64/Debug/wxCore64d.lib
LDDEPS += ../../../../build/windows/gmake2/output/x64/Debug/Engine.lib ../../../../build/windows/gmake2/output/x64/Debug/Memory64d.lib ../../../../build/windows/gmake2/output/x64/Debug/wxBase64d.lib ../../../../build/windows/gmake2/output/x64/Debug/wxCore64d.lib
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -shared -Wl,--out-implib="../../../../build/windows/gmake2/output/x64/Debug/wxMedia64d.lib"
define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\bin (mkdir ..\..\..\..\..\workingdir\bin)
	IF EXIST ..\..\..\..\build\windows\gmake2\output\x64\Debug\wxMedia64d.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Debug\wxMedia64d.dll ..\..\..\..\..\workingdir\bin > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Debug\wxMedia64d.dll ..\..\..\..\..\workingdir\bin > nul)
endef
endif

ifeq ($(config),release_x64)
RESCOMP = windres
TARGETDIR = ../../../../build/windows/gmake2/output/x64/Release
TARGET = $(TARGETDIR)/wxMedia64.dll
OBJDIR = ../../../../build/windows/gmake2/intermediate/x64/Release/wxMedia
DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -DNDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DWXBUILDING -DwxUSE_ZLIB_H_IN_PATH -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NON_CONFORMING_SWPRINTFS=1 -D_SCL_SECURE_NO_WARNINGS=1 -DXML_STATIC -DWXMAKINGDLL_MEDIA -DWXUSINGDLL -D__WXMSW__
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
LIBS += ../../../../build/windows/gmake2/output/x64/Release/Engine.lib ../../../../build/windows/gmake2/output/x64/Release/Memory64.lib ../../../../build/windows/gmake2/output/x64/Release/wxBase64.lib ../../../../build/windows/gmake2/output/x64/Release/wxCore64.lib
LDDEPS += ../../../../build/windows/gmake2/output/x64/Release/Engine.lib ../../../../build/windows/gmake2/output/x64/Release/Memory64.lib ../../../../build/windows/gmake2/output/x64/Release/wxBase64.lib ../../../../build/windows/gmake2/output/x64/Release/wxCore64.lib
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake2/output/x64/Release/wxMedia64.lib"
define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\bin (mkdir ..\..\..\..\..\workingdir\bin)
	IF EXIST ..\..\..\..\build\windows\gmake2\output\x64\Release\wxMedia64.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Release\wxMedia64.dll ..\..\..\..\..\workingdir\bin > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Release\wxMedia64.dll ..\..\..\..\..\workingdir\bin > nul)
endef
endif

ifeq ($(config),debug_clang_x64)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
TARGETDIR = ../../../../build/windows/gmake2/output/x64/Debug_Clang
TARGET = $(TARGETDIR)/wxMedia64d.dll
OBJDIR = ../../../../build/windows/gmake2/intermediate/x64/Debug_Clang/wxMedia
DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -D_DEBUG -DDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DWXBUILDING -DwxUSE_ZLIB_H_IN_PATH -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NON_CONFORMING_SWPRINTFS=1 -D_SCL_SECURE_NO_WARNINGS=1 -DXML_STATIC -DWXMAKINGDLL_MEDIA -DWXUSINGDLL -D__WXMSW__
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -ffast-math -O0 -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -ffast-math -O0 -g -Wall -Wextra -std=c++1z -fno-rtti
LIBS += ../../../../build/windows/gmake2/output/x64/Debug_Clang/Engine.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/Memory64d.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/wxBase64d.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/wxCore64d.lib
LDDEPS += ../../../../build/windows/gmake2/output/x64/Debug_Clang/Engine.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/Memory64d.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/wxBase64d.lib ../../../../build/windows/gmake2/output/x64/Debug_Clang/wxCore64d.lib
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -shared -Wl,--out-implib="../../../../build/windows/gmake2/output/x64/Debug_Clang/wxMedia64d.lib"
define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\bin (mkdir ..\..\..\..\..\workingdir\bin)
	IF EXIST ..\..\..\..\build\windows\gmake2\output\x64\Debug_Clang\wxMedia64d.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Debug_Clang\wxMedia64d.dll ..\..\..\..\..\workingdir\bin > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Debug_Clang\wxMedia64d.dll ..\..\..\..\..\workingdir\bin > nul)
endef
endif

ifeq ($(config),release_clang_x64)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
TARGETDIR = ../../../../build/windows/gmake2/output/x64/Release_Clang
TARGET = $(TARGETDIR)/wxMedia64.dll
OBJDIR = ../../../../build/windows/gmake2/intermediate/x64/Release_Clang/wxMedia
DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -DNDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DWXBUILDING -DwxUSE_ZLIB_H_IN_PATH -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NON_CONFORMING_SWPRINTFS=1 -D_SCL_SECURE_NO_WARNINGS=1 -DXML_STATIC -DWXMAKINGDLL_MEDIA -DWXUSINGDLL -D__WXMSW__
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
LIBS += ../../../../build/windows/gmake2/output/x64/Release_Clang/Engine.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/Memory64.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/wxBase64.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/wxCore64.lib
LDDEPS += ../../../../build/windows/gmake2/output/x64/Release_Clang/Engine.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/Memory64.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/wxBase64.lib ../../../../build/windows/gmake2/output/x64/Release_Clang/wxCore64.lib
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake2/output/x64/Release_Clang/wxMedia64.lib"
define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\bin (mkdir ..\..\..\..\..\workingdir\bin)
	IF EXIST ..\..\..\..\build\windows\gmake2\output\x64\Release_Clang\wxMedia64.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Release_Clang\wxMedia64.dll ..\..\..\..\..\workingdir\bin > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Release_Clang\wxMedia64.dll ..\..\..\..\..\workingdir\bin > nul)
endef
endif

ifeq ($(config),profile_x64)
RESCOMP = windres
TARGETDIR = ../../../../build/windows/gmake2/output/x64/Profile
TARGET = $(TARGETDIR)/wxMedia64p.dll
OBJDIR = ../../../../build/windows/gmake2/intermediate/x64/Profile/wxMedia
DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -DNDEBUG -DSHIB_PROFILE -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DWXBUILDING -DwxUSE_ZLIB_H_IN_PATH -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NON_CONFORMING_SWPRINTFS=1 -D_SCL_SECURE_NO_WARNINGS=1 -DXML_STATIC -DWXMAKINGDLL_MEDIA -DWXUSINGDLL -D__WXMSW__
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
LIBS += ../../../../build/windows/gmake2/output/x64/Profile/Engine.lib ../../../../build/windows/gmake2/output/x64/Profile/Memory64p.lib ../../../../build/windows/gmake2/output/x64/Profile/wxBase64p.lib ../../../../build/windows/gmake2/output/x64/Profile/wxCore64p.lib
LDDEPS += ../../../../build/windows/gmake2/output/x64/Profile/Engine.lib ../../../../build/windows/gmake2/output/x64/Profile/Memory64p.lib ../../../../build/windows/gmake2/output/x64/Profile/wxBase64p.lib ../../../../build/windows/gmake2/output/x64/Profile/wxCore64p.lib
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake2/output/x64/Profile/wxMedia64p.lib"
define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\bin (mkdir ..\..\..\..\..\workingdir\bin)
	IF EXIST ..\..\..\..\build\windows\gmake2\output\x64\Profile\wxMedia64p.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Profile\wxMedia64p.dll ..\..\..\..\..\workingdir\bin > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Profile\wxMedia64p.dll ..\..\..\..\..\workingdir\bin > nul)
endef
endif

ifeq ($(config),profile_clang_x64)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
TARGETDIR = ../../../../build/windows/gmake2/output/x64/Profile_Clang
TARGET = $(TARGETDIR)/wxMedia64p.dll
OBJDIR = ../../../../build/windows/gmake2/intermediate/x64/Profile_Clang/wxMedia
DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -DNDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DWXBUILDING -DwxUSE_ZLIB_H_IN_PATH -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NON_CONFORMING_SWPRINTFS=1 -D_SCL_SECURE_NO_WARNINGS=1 -DXML_STATIC -DWXMAKINGDLL_MEDIA -DWXUSINGDLL -D__WXMSW__
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
LIBS += ../../../../build/windows/gmake2/output/x64/Profile_Clang/Engine.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/Memory64p.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/wxBase64p.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/wxCore64p.lib
LDDEPS += ../../../../build/windows/gmake2/output/x64/Profile_Clang/Engine.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/Memory64p.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/wxBase64p.lib ../../../../build/windows/gmake2/output/x64/Profile_Clang/wxCore64p.lib
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake2/output/x64/Profile_Clang/wxMedia64p.lib"
define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\bin (mkdir ..\..\..\..\..\workingdir\bin)
	IF EXIST ..\..\..\..\build\windows\gmake2\output\x64\Profile_Clang\wxMedia64p.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Profile_Clang\wxMedia64p.dll ..\..\..\..\..\workingdir\bin > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Profile_Clang\wxMedia64p.dll ..\..\..\..\..\workingdir\bin > nul)
endef
endif

ifeq ($(config),optimized_debug_x64)
RESCOMP = windres
TARGETDIR = ../../../../build/windows/gmake2/output/x64/Optimized_Debug
TARGET = $(TARGETDIR)/wxMedia64od.dll
OBJDIR = ../../../../build/windows/gmake2/intermediate/x64/Optimized_Debug/wxMedia
DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -D_DEBUG -DDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DWXBUILDING -DwxUSE_ZLIB_H_IN_PATH -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NON_CONFORMING_SWPRINTFS=1 -D_SCL_SECURE_NO_WARNINGS=1 -DXML_STATIC -DWXMAKINGDLL_MEDIA -DWXUSINGDLL -D__WXMSW__
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
LIBS += ../../../../build/windows/gmake2/output/x64/Optimized_Debug/Engine.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/Memory64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/wxBase64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/wxCore64od.lib
LDDEPS += ../../../../build/windows/gmake2/output/x64/Optimized_Debug/Engine.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/Memory64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/wxBase64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug/wxCore64od.lib
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake2/output/x64/Optimized_Debug/wxMedia64od.lib"
define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\bin (mkdir ..\..\..\..\..\workingdir\bin)
	IF EXIST ..\..\..\..\build\windows\gmake2\output\x64\Optimized_Debug\wxMedia64od.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Optimized_Debug\wxMedia64od.dll ..\..\..\..\..\workingdir\bin > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Optimized_Debug\wxMedia64od.dll ..\..\..\..\..\workingdir\bin > nul)
endef
endif

ifeq ($(config),optimized_debug_clang_x64)
ifeq ($(origin CC), default)
  CC = clang
endif
ifeq ($(origin CXX), default)
  CXX = clang++
endif
ifeq ($(origin AR), default)
  AR = ar
endif
TARGETDIR = ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang
TARGET = $(TARGETDIR)/wxMedia64od.dll
OBJDIR = ../../../../build/windows/gmake2/intermediate/x64/Optimized_Debug_Clang/wxMedia
DEFINES += -DUNICODE -D_UNICODE -DEA_COMPILER_NO_RTTI -D_DEBUG -DDEBUG -DWIN32 -D_WINDOWS -DWIN64 -DNOPCH -DWXBUILDING -DwxUSE_ZLIB_H_IN_PATH -D_CRT_SECURE_NO_DEPRECATE=1 -D_CRT_NON_CONFORMING_SWPRINTFS=1 -D_SCL_SECURE_NO_WARNINGS=1 -DXML_STATIC -DWXMAKINGDLL_MEDIA -DWXUSINGDLL -D__WXMSW__
ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra
ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -flto -ffast-math -O3 -g -Wall -Wextra -std=c++1z -fno-rtti
LIBS += ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/Engine.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/Memory64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/wxBase64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/wxCore64od.lib
LDDEPS += ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/Engine.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/Memory64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/wxBase64od.lib ../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/wxCore64od.lib
ALL_LDFLAGS += $(LDFLAGS) -L/usr/lib64 -m64 -flto -shared -Wl,--out-implib="../../../../build/windows/gmake2/output/x64/Optimized_Debug_Clang/wxMedia64od.lib"
define POSTBUILDCMDS
	@echo Running postbuild commands
	IF NOT EXIST ..\..\..\..\..\workingdir\bin (mkdir ..\..\..\..\..\workingdir\bin)
	IF EXIST ..\..\..\..\build\windows\gmake2\output\x64\Optimized_Debug_Clang\wxMedia64od.dll\ (xcopy /Q /E /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Optimized_Debug_Clang\wxMedia64od.dll ..\..\..\..\..\workingdir\bin > nul) ELSE (xcopy /Q /Y /I ..\..\..\..\build\windows\gmake2\output\x64\Optimized_Debug_Clang\wxMedia64od.dll ..\..\..\..\..\workingdir\bin > nul)
endef
endif

# Per File Configurations
# #############################################


# File sets
# #############################################

OBJECTS :=

OBJECTS += $(OBJDIR)/dummy.o
OBJECTS += $(OBJDIR)/mediactrl_am.o
OBJECTS += $(OBJDIR)/mediactrl_qt.o
OBJECTS += $(OBJDIR)/mediactrl_wmp10.o
OBJECTS += $(OBJDIR)/mediactrlcmn.o

# Rules
# #############################################

all: prebuild prelink $(TARGET) | $(TARGETDIR) $(OBJDIR)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) | $(TARGETDIR)
	@echo Linking wxMedia
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning wxMedia
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH) | $(OBJDIR) $(PCH_PLACEHOLDER)
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
$(PCH_PLACEHOLDER): $(GCH) | $(OBJDIR)
	$(SILENT) touch "$@"
else
$(OBJECTS): | $(OBJDIR)
endif


# File Rules
# #############################################

$(OBJDIR)/dummy.o: ../../../../../src/Dependencies/wxWidgets/src/common/dummy.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mediactrlcmn.o: ../../../../../src/Dependencies/wxWidgets/src/common/mediactrlcmn.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mediactrl_am.o: ../../../../../src/Dependencies/wxWidgets/src/msw/mediactrl_am.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mediactrl_qt.o: ../../../../../src/Dependencies/wxWidgets/src/msw/mediactrl_qt.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/mediactrl_wmp10.o: ../../../../../src/Dependencies/wxWidgets/src/msw/mediactrl_wmp10.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include "$(PCH_PLACEHOLDER).d"
endif